# -*- coding: utf-8 -*-
"""Ejericios_Unidad_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UlzSENMwV3ItLHJOtkkD0mnd2De5ozA6

**Ejercicio 1**

Escribir una función que aplique un descuento a un precio y otra que aplique el IVA a un precio. Escribir una tercera función que reciba un diccionario con los precios y porcentajes de una cesta de la compra, y una de las funciones anteriores, y utilice la función pasada para aplicar los descuentos o el IVA a los productos de la cesta y devolver el precio final de la cesta.
"""

def aplicar_descuento(precio, decuento_procentaje):
  descuento = precio * decuento_procentaje / 100
  return precio - descuento

def aplicar_IVA (precio, iva_procentaje):
  iva = precio * iva_procentaje / 100
  return precio + iva # Fixed typo: pricio changed to precio

def precio_final (cesta, funcion_aplicar):
  precio_total = 0
  for producto, precio in cesta.items():
    precio_total += funcion_aplicar(precio,10) # Assuming 10 is the intended percentage
  return precio_total # Moved return outside the loop and removed semicolon

#ejemplo de uso
cesta_ejemplo = {'manzanas': 1.5, 'pan': 2.0, 'leche': 1.2} # Fixed dictionary syntax

#precio aplicando descuento
precio_con_descuento = precio_final(cesta_ejemplo, aplicar_descuento)
print(f"precio total con descuento:  {precio_con_descuento})")

#precio aplicando iva
precio_con_iva = precio_final(cesta_ejemplo, aplicar_IVA)
print(f"precio total con iva: {precio_con_iva}")

#precio final
precio_final = precio_final(cesta_ejemplo, aplicar_descuento)
print(f"precio final: {precio_final}")

"""**Ejercicio 2**

Escribir una función que simule una calculadora científica que permita calcular el seno, coseno, tangente, exponencial y logaritmo neperiano. La función preguntará al usuario el valor y la función a aplicar, y mostrará por pantalla una tabla con los enteros de 1 al valor introducido y el resultado de aplicar la función a esos enteros.
"""

import math

def calculadora_cientifica():
    valor = int(input("Introduce un valor:"))
    funcion_str = input("Escribe: seno, cos, tan, expo, log):").lower().strip()

    funcion_aplicar = None
    if funcion_str == "seno":
        funcion_aplicar = math.sin
    elif funcion_str == "cos":
        funcion_aplicar = math.cos
    elif funcion_str == "tan":
        funcion_aplicar = math.tan
    elif funcion_str == "expo":
        funcion_aplicar = math.exp
    elif funcion_str == "log":
        funcion_aplicar = math.log
    else:
        print("Función no reconocida. Intente de nuevo.")
        return

    print("\nTabla de resultados:")
    print("--------------------------------")
    print(f"| Número | {funcion_str.capitalize()} |")
    print("--------------------------------")

    for i in range(1, valor + 1):
        try:
            resultado = funcion_aplicar(i)
            print(f"| {i:<6} | {resultado:^10.4f} |")
        except ValueError:
            print(f"| {i:<6} | {'Error':^10} |") # Handle cases like log(0)
    print("--------------------------------")

# Example usage (optional, for testing the function after definition)
if __name__ == '__main__':
    calculadora_cientifica()



"""**Ejercicio 3**

Escribir una función que reciba otra función y una lista, y devuelva otra lista con el resultado de aplicar la función dada a cada uno de los elementos de la lista.
"""

def aplicar_funcion_a_lista(funcion, lista):
    resultado = []
    for elemento in lista:
        resultado.append(funcion(elemento))
    return resultado
def doble(numero):
    return numero * 2
numeros = [1, 2, 3, 4, 5]
resultado = aplicar_funcion_a_lista(doble, numeros)
print(resultado)

"""**Ejercicio 4**

Escribir una función que reciba otra función booleana y una lista, y devuelva otra lista con los elementos de la lista que devuelvan True al aplicarles la función booleana.
"""

def filtrar_lista(funcion, lista):
    "Filtrar"
    lista_filtrada = []

    for elemento in lista:
        if funcion(elemento) == True:
            lista_filtrada.append(elemento)

    return lista_filtrada

def es_par(n):
    return n % 2 == 0

numeros = [1, 2, 3, 4]

resultado = filtrar_lista(es_par, numeros)

print(f"Lista: {numeros}")
print(f"Numero que cumplen (pares): {resultado}")



"""**Ejercicio 5**

Escribir una función que reciba una frase y devuelva un diccionario con las palabras que contiene y su longitud.
"""

def diccionario_palabras(frase):
    palabras = frase.split()
    resultado = {}

    for palabra in palabras:
        resultado[palabra] = len(palabra)
    return resultado

frase = "Saludos desde 2K"
diccionario = diccionario_palabras(frase)

print(f"Frase: {frase}")
print(f"Diccionario de palabras: {diccionario}")



"""**Ejercicio 6**

Escribir una función reciba una lista de notas y devuelva la lista de calificaciones correspondientes a esas notas.
"""

def calificar_notas(notas):
    resultado = []

    for nota in notas:
        if nota >= 5:
            resultado.append("Aprobado")
        else:
            resultado.append("Suspenso")
    return resultado

mis_notas = [1, 2, 3, 4,5,6,7,8,9,10]
print(calificar_notas(mis_notas))

"""**Ejercicio 7**

Escribir una función reciba un diccionario con las asignaturas y las notas de un alumno y devuelva otro diccionario con las asignaturas en mayúsculas y las calificaciones correspondientes a las notas.
"""

def transformar_notas(diccionario_original):
    nuevo_diccionario = {}

    for materia, nota in diccionario_original.items():
        materia_grande = materia.upper()
        if nota >= 5:
            resultado = "APROBADO"
        else:
            resultado = "SUSPENSO"
        nuevo_diccionario[materia_grande] = resultado
    return nuevo_diccionario

mi_colegio = {"historia": 3, "dibujo": 8}
print(transformar_notas(mi_colegio))

"""**Ejercicio 8**

Escribir una función reciba un diccionario con las asignaturas y las notas de un alumno y devuelva otro diccionario con las asignaturas en mayúsculas y las calificaciones correspondientes a las notas aprobadas.
"""

def asignaturas (notas):
    resultado = {}

    for materia, nota in notas.items():
        if nota >= 5:
            nombre_pro = materia.upper()
            resultado[nombre_pro] = "APROBADO"
    return resultado

mis_notas = {"ESIT": 8, "DAPI": 8, "SIHD": 5}
print(asignaturas (mis_notas))

"""**Ejercicio 9**

Escribir una función que calcule el módulo de un vector.
"""

def calcular_modulo(vector):
    suma_cuadrados = 0

    for componente in vector:
        suma_cuadrados = suma_cuadrados + (componente ** 2)
    modulo = suma_cuadrados ** 0.5
    return modulo

mi_vector = [3, 4]
print(f"El módulo de {mi_vector} es: {calcular_modulo(mi_vector)}")

"""**Ejercicio 11**

Escribir una función que reciba una muestra de números y devuelva los valores atípicos, es decir, los valores cuya puntuación típica sea mayor que 3 o menor que -3. Nota: La puntuación típica de un valor se obtiene restando la media y dividiendo por la desviación típica de la muestra.
"""

import statistics
def buscar_valores_extremos(datos):
    media = statistics.mean(datos)
    desviacion = statistics.stdev(datos)
    atipicos = []

    for x in datos:
        z_score = (x - media) / desviacion
        if abs(z_score) > 1.5:
            atipicos.append(x)

    return atipicos

precios_gpu = [300, 310, 290, 305, 315, 2000]
resultado = buscar_valores_extremos(precios_gpu)

print(f"Los valores atipicos son: {resultado}")

