# -*- coding: utf-8 -*-
"""EjerciciosFuncionesUT4 (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uabt6IsU4Y6dsnhCkLHA3YP-9LsWaixB

1. Escribir una función que muestre por pantalla el saludo ¡Hola amiga! cada vez que se la invoque.
"""

def saludar():
  print("¡Hola amiga!")

saludar()

"""2. Escribir una función a la que se le pase una cadena <nombre> y muestre por pantalla el saludo ¡hola <nombre>!.

"""

n = input( "Ingresa tu nombre: ")
def saludo(nombre):
  print(f"¡Hola {nombre}!")
saludo(n)

"""3. Escribir una función que reciba un número entero positivo y devuelva su factorial."""

def calcular_factorial(n):
  resultado = 1
  for i in range(1, n + 1):
        resultado = resultado * i
  return resultado
numero = 6
print(f"El factorial de {numero} es: {calcular_factorial(numero)}")

"""4. Escribir una función que calcule el total de una factura tras aplicarle el IVA. La función debe recibir la cantidad sin IVA y el porcentaje de IVA a aplicar, y devolver el total de la factura. Si se invoca la función sin pasarle el porcentaje de IVA, deberá aplicar un 21%."""

def invoice(amount, vat=21):
    return amount + amount*vat/100

print(invoice(1000,10))
print(invoice(1000))

"""5. Escribir una función que calcule el área de un círculo y otra que calcule el volumen de un cilindro usando la primera función."""

import math

def area_circulo(radio):
  return math.pi * (radio ** 2)

def volumen_cilindro(radio, altura):
  area_base = area_circulo(radio)
  return area_base * altura

radio_circulo = 3
altura_cilindro = 15
print(f"area del círculo con radio {radio_circulo} es:{area_circulo(radio_circulo):.2f}")
print(f"volumen del cilindro con radio {radio_circulo} y altura {altura_cilindro} es: {volumen_cilindro(radio_circulo, altura_cilindro):.2f}")

"""6. Escribir una función que reciba una muestra de números en una lista y devuelva su media."""

def calcular_media(muestra):
  if not muestra:
    return 0
  return sum(muestra) / len(muestra)

numeros = [1, 2, 3,]
media = calcular_media(numeros)
print(f"La media es: {media}")

"""7. Escribir una función que reciba una muestra de números en una lista y devuelva otra lista con sus cuadrados."""

def calcular_cuadrados(lista_numeros):
  return [numero ** 2 for numero in lista_numeros]

muestra = [1, 2, 3,]
print(f"Los cuadrados del {muestra} son: {calcular_cuadrados(muestra)}")

"""8. Escribir una función que reciba una muestra de números en una lista y devuelva un diccionario con su media, varianza y desviación típica."""

import math

def calcular_estadisticas_muestra(lista_numeros):
  if not lista_numeros:
    return {"media": 0, "varianza": 0, "desviacion_tipica": 0}

  media = sum(lista_numeros) / len(lista_numeros)
  varianza = sum([(x - media) ** 2 for x in lista_numeros]) / len(lista_numeros)
  desviacion_tipica = math.sqrt(varianza)

  return {
      "media": media,
      "varianza": varianza,
      "desviacion_tipica": desviacion_tipica
  }

muestra = [1, 2, 3]
stats = calcular_estadisticas_muestra(muestra)
print(f"Estadísticas de la muestra {muestra}:\nMedia: {stats['media']:.2f}\nVarianza: {stats['varianza']:.2f}\nDesviación Típica: {stats['desviacion_tipica']:.2f}")

"""9. Escribir una función que calcule el máximo común divisor de dos números y otra que calcule el mínimo común múltiplo."""

def mcd(n, m):
  while(m):
    n, m = m, n % m
  return n

def mcm(n, m):
  return abs(n*m) // mcd(n, m)

a = 3
b = 15

print(f"El MCD de {a} y {b} es: {mcd(a, b)}")
print(f"El MCM de {a} y {b} es: {mcm(a, b)}")

"""10. Escribir una función que convierta un número decimal en binario y otra que convierta un número binario en decimal."""

def decimal_a_binario(decimal):
  if decimal == 0:
    return "0"
  binario = ""
  while decimal > 0:
    binario = str(decimal % 2) + binario
    decimal //= 2
  return binario

def binario_a_decimal(binario):
  decimal = 0
  for i, digito in enumerate(reversed(binario)):
    if digito == '1':
      decimal += 2 ** i
  return decimal

num_decimal = 12
num_binario = "101"

binario_resultante = decimal_a_binario(num_decimal)
decimal_resultante = binario_a_decimal(num_binario)

print(f"El número decimal {num_decimal} en binario es: {binario_resultante}")
print(f"El número binario {num_binario} en decimal es: {decimal_resultante}")

"""11. Escribir un programa que reciba una cadena de caracteres y devuelva un diccionario con cada palabra que contiene y su frecuencia. Escribir otra función que reciba el diccionario generado con la función anterior y devuelva una tupla con la palabra más repetida y su frecuencia."""

from collections import Counter

def contar_frecuencia_palabras(cadena):
  cadena_limpia = ''.join(c.lower() if c.isalnum() or c.isspace() else ' ' for c in cadena)
  palabras = cadena_limpia.split()
  return dict(Counter(palabras))

def palabra_mas_repetida(diccionario_frecuencias):
  if not diccionario_frecuencias:
    return (None, 0)

  palabra_max = None
  frecuencia_max = 0
  for palabra, frecuencia in diccionario_frecuencias.items():
    if frecuencia > frecuencia_max:
      frecuencia_max = frecuencia
      palabra_max = palabra
  return (palabra_max, frecuencia_max)

texto = "Hola amigos :3"
frecuencias = contar_frecuencia_palabras(texto)
print(f"Frecuencia de palabras: {frecuencias}")

mas_repetida, freq = palabra_mas_repetida(frecuencias)
print(f"La palabra más repetida es '{mas_repetida}' con una frecuencia de {freq}.")